In [1]:
import pandas as pd
from datetime import datetime
import csv

Đầu tiên, em sẽ xem thử output hiện tại đang có format thế nào

In [2]:
!head out.txt

["23/06/2022", "Top", 85808.0]	null
["23/06/2022", "Western Dress", 149805.0]	null
["23/06/2022", "kurta", 463975.0]	null
["24/04/2022", "Blouse", 14997.0]	null
["24/04/2022", "Bottom", 7850.0]	null
["24/04/2022", "Ethnic Dress", 10303.0]	null
["24/04/2022", "Saree", 5781.0]	null
["24/04/2022", "Set", 1025338.0]	null
["24/04/2022", "Top", 131976.0]	null
["24/04/2022", "Western Dress", 156369.0]	null

Có thể thấy là file được chia ra làm 2 phần riêng biệt, bên trái là 3 cột đáp án, bên phải là giá trị null.

Do đó em sẽ thực hiện các bước xử lý như sau để định dạng lại kết quả:
- 1: Loại bỏ các giá trị `null` ở cuối dòng.
- 2: Tách các giá trị ở bên trái ra thành các cột riêng biệt.
- 3: Thêm vào từng dòng vào `dictionary` và sau đó lưu xuống csv bằng pandas.

In [3]:
d = {
    "report_date": [],
    "category": [],
    "revenue": [],
}

with open('out.txt', 'r') as f:
    lines = f.read().split('\n')
    for line in lines:
        line = line.strip()
        if line == '':
            continue

        # seperate the 3 columns and null        
        key, _ = line.split('\t')
        
        # remove '[' and ']'
        key = key[1: -1]

        report_date, category, revenue = list(csv.reader([key]))[0]
        d['report_date'].append(report_date.strip().replace('"', ''))
        d['category'].append(category.strip().replace('"', ''))
        d['revenue'].append(revenue.strip().replace('"', ''))

df = pd.DataFrame(d)

In [4]:
df

    report_date       category   revenue
0    23/06/2022            Top   85808.0
1    23/06/2022  Western Dress  149805.0
2    23/06/2022          kurta  463975.0
3    24/04/2022         Blouse   14997.0
4    24/04/2022         Bottom    7850.0
..          ...            ...       ...
731  05/06/2022          Saree    5741.0
732  05/06/2022            Set  863267.0
733  05/06/2022            Top   95967.0
734  05/06/2022  Western Dress  168370.0
735  05/06/2022          kurta  668773.0

[736 rows x 3 columns]

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 736 entries, 0 to 735
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   report_date  736 non-null    object
 1   category     736 non-null    object
 2   revenue      736 non-null    object
dtypes: object(3)
memory usage: 17.4+ KB

Có thể thấy dữ liệu đã đúng format tuy nhiên vẫn chưa được sort. Để sort được theo `report_date` thì em sẽ convert nó qua kiêu `datetime`.

In [6]:
df['report_date'] = pd.to_datetime(df['report_date'], format='%d/%m/%Y')
df

    report_date       category   revenue
0    2022-06-23            Top   85808.0
1    2022-06-23  Western Dress  149805.0
2    2022-06-23          kurta  463975.0
3    2022-04-24         Blouse   14997.0
4    2022-04-24         Bottom    7850.0
..          ...            ...       ...
731  2022-06-05          Saree    5741.0
732  2022-06-05            Set  863267.0
733  2022-06-05            Top   95967.0
734  2022-06-05  Western Dress  168370.0
735  2022-06-05          kurta  668773.0

[736 rows x 3 columns]

In [7]:
df = df.sort_values(by=['report_date', 'category'])
df

    report_date       category  revenue
495  2022-03-31            Set  47217.0
496  2022-03-31            Top   4065.0
497  2022-03-31  Western Dress   2198.0
498  2022-03-31          kurta  30533.0
372  2022-04-01         Blouse   4516.0
..          ...            ...      ...
396  2022-07-01   Ethnic Dress    690.0
397  2022-07-01            Set  45205.0
398  2022-07-01            Top   9314.0
399  2022-07-01  Western Dress  24044.0
400  2022-07-01          kurta  35416.0

[736 rows x 3 columns]

Bây giờ dữ liệu đã được sort, tuy nhiên cột `report_date` lại đang bị sai format D:, do đó em sẽ convert lại từ `datetime` sang `str`.

In [8]:
df['report_date'] = df['report_date'].dt.strftime('%d/%m/%Y')
df

    report_date       category  revenue
495  31/03/2022            Set  47217.0
496  31/03/2022            Top   4065.0
497  31/03/2022  Western Dress   2198.0
498  31/03/2022          kurta  30533.0
372  01/04/2022         Blouse   4516.0
..          ...            ...      ...
396  01/07/2022   Ethnic Dress    690.0
397  01/07/2022            Set  45205.0
398  01/07/2022            Top   9314.0
399  01/07/2022  Western Dress  24044.0
400  01/07/2022          kurta  35416.0

[736 rows x 3 columns]

Như vậy việc xử lý dữ liệu cuối cùng cũng xong. Vậy việc cuối cùng cần làm chính là lưu xuống file csv.

In [9]:
df.set_index('report_date').to_csv('output.csv')

Kiểm tra thử format của file output.csv

In [10]:
!head output.csv

report_date,category,revenue
31/03/2022,Set,47217.0
31/03/2022,Top,4065.0
31/03/2022,Western Dress,2198.0
31/03/2022,kurta,30533.0
01/04/2022,Blouse,4516.0
01/04/2022,Bottom,360.0
01/04/2022,Ethnic Dress,11466.0
01/04/2022,Set,394350.0
01/04/2022,Top,52031.0