## Connect to MongoDB using pymongo

In [31]:
# Install the pymongo package
!pip install --upgrade "pymongo[srv]"

Requirement already satisfied: pymongo[srv] in /usr/local/lib/python3.11/dist-packages (4.12.1)
WARNING: pymongo 4.12.1 does not provide the extra 'srv'
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.11/dist-packages (from pymongo[srv]) (2.7.0)

In [32]:
# Necessary packages and classes
from pymongo.mongo_client import MongoClient
from pymongo.server_api import ServerApi

# Required URI to connect to the databases, which must be given in advance
uri = "mongodb+srv://student:student@bigdata.zyjwsrz.mongodb.net/"

# Create a new client and connect to the server
client = MongoClient(uri, server_api=ServerApi('1'))

# Send a ping to confirm a successful connection
try:
    client.admin.command('ping')
    print("Pinged your deployment. You successfully connected to MongoDB!")
except Exception as e:
    print(e)

Pinged your deployment. You successfully connected to MongoDB!

In [33]:
# Get the data records in the collection 'users' of the database 'sample_mflix'
# These names must be given in advance
mongoData = client['Examples']['dishes']
# Check whether the data is get successfully by having a look at the first record
for c in mongoData.find():
  print(c)
  break

{'_id': ObjectId('670c8bcc5dafe0691fff69df'), 'Code': 'U0GT', 'Dish Name': 'Spaghetti Carbonara', 'Ingredients': 'Spaghetti, eggs, pancetta, parmesan, black pepper'}

In [34]:
# Transfer the data to a pandas DF for easy manipulation
import pandas as pd
pdDF = pd.DataFrame(list(mongoData.find()))
display(pdDF)
# You may need to convert a pandas DF to a Spark DF for further use

,_id,Code,Dish Name,Ingredients
0,670c8bcc5dafe0691fff69df,U0GT,Spaghetti Carbonara,"Spaghetti, eggs, pancetta, parmesan, black pepper"
1,670c8bcc5dafe0691fff69e1,V4WJ,Beef Tacos,"Beef, taco shells, lettuce, tomato, cheese, salsa"
2,670c8bcc5dafe0691fff69e3,9U84,Tom Yum Soup,"Shrimp, lemongrass, lime juice, chili, mushrooms"
3,670c8bcc5dafe0691fff69e5,OWSH,Sushi Roll,"Rice, seaweed, fish, cucumber, avocado"
4,670c8bcc5dafe0691fff69e9,TPPS,Spaghetti Carbonara,"Spaghetti, eggs, pancetta, parmesan, black pepper"
...,...,...,...,...
95,670c8bcc5dafe0691fff6a33,LCER,Tom Yum Soup,"Shrimp, lemongrass, lime juice, chili, mushrooms"
96,670c8bcc5dafe0691fff6a3b,HS3J,Beef Tacos,"Beef, taco shells, lettuce, tomato, cheese, salsa"
97,670c8bcc5dafe0691fff6a3c,2LJ1,Margherita Pizza,"Pizza dough, tomatoes, mozzarella, basil"
98,670c8bcc5dafe0691fff6a3f,3TC8,Sushi Roll,"Rice, seaweed, fish, cucumber, avocado"
99,670c8bcc5dafe0691fff6a40,UFJJ,Pancakes,"Flour, eggs, milk, sugar, baking powder, syrup"

In [35]:
# Close the connection when done
client.close()

## Connect to MongoDB using PySpark connection

In [36]:
# install java
!apt-get update
!apt-get install openjdk-8-jdk-headless -qq > /dev/null
# install spark (change the version number if needed)
!wget -q https://downloads.apache.org/spark/spark-3.5.5/spark-3.5.5-bin-hadoop3.tgz
# unzip the spark file to the current folder
!tar xf spark-3.5.5-bin-hadoop3.tgz
# set your spark folder to your system path environment.
import os
os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-8-openjdk-amd64"
os.environ["SPARK_HOME"] = "/content/spark-3.5.5-bin-hadoop3"

Hit:1 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease
Hit:2 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:3 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  InRelease
Hit:4 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:5 https://r2u.stat.illinois.edu/ubuntu jammy InRelease
Hit:6 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:7 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:8 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Hit:9 https://ppa.launchpadcontent.net/graphics-drivers/ppa/ubuntu jammy InRelease
Hit:10 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Reading package lists... Done
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)

In [37]:
# start pyspark
!pip install findspark
import findspark
findspark.init()

Requirement already satisfied: findspark in /usr/local/lib/python3.11/dist-packages (2.0.1)

In [38]:
# Neccessary packages and classes
import pyspark
from pyspark.sql import SparkSession
# Create a new client and connect to the server
uri = "mongodb+srv://student:student@bigdata.zyjwsrz.mongodb.net/"
spark = SparkSession \
    .builder.master("local")\
    .appName("Connect to MongoDB Cloud")\
    .config("spark.mongodb.input.uri", uri)\
    .config("spark.mongodb.output.uri", uri)\
    .config("spark.jars.packages", "org.mongodb.spark:mongo-spark-connector_2.12:3.0.1")\
    .getOrCreate()
  # spark.mongodb.input.uri, spark.mongodb.output.uri, and spark.jars.packages must be specified

In [39]:
sparkDF =  spark.read.format("com.mongodb.spark.sql.DefaultSource")\
    .option("uri",uri)\
    .option("database", "Examples")\
    .option("collection", "dishes")\
    .load()
sparkDF.show()
# format and uri must be specified, uri must be the same as above

+----+--------------------+--------------------+--------------------+
|Code|           Dish Name|         Ingredients|                 _id|
+----+--------------------+--------------------+--------------------+
|U0GT| Spaghetti Carbonara|Spaghetti, eggs, ...|{670c8bcc5dafe069...|
|V4WJ|          Beef Tacos|Beef, taco shells...|{670c8bcc5dafe069...|
|9U84|        Tom Yum Soup|Shrimp, lemongras...|{670c8bcc5dafe069...|
|OWSH|          Sushi Roll|Rice, seaweed, fi...|{670c8bcc5dafe069...|
|TPPS| Spaghetti Carbonara|Spaghetti, eggs, ...|{670c8bcc5dafe069...|
|PDYD|Chicken Caesar Salad|Chicken, romaine ...|{670c8bcc5dafe069...|
|R08D|            Pad Thai|Rice noodles, shr...|{670c8bcc5dafe069...|
|L7XN|            Pancakes|Flour, eggs, milk...|{670c8bcc5dafe069...|
|VNKN|      Butter Chicken|Chicken, butter, ...|{670c8bcc5dafe069...|
|KFC7|Chicken Caesar Salad|Chicken, romaine ...|{670c8bcc5dafe069...|
|Q2BE|    Margherita Pizza|Pizza dough, toma...|{670c8bcc5dafe069...|
|LK91|        Tom Yum Soup|Shrimp, lemongras...|{670c8bcc5dafe069...|
|5905|            Pad Thai|Rice noodles, shr...|{670c8bcc5dafe069...|
|H1L1|            Pancakes|Flour, eggs, milk...|{670c8bcc5dafe069...|
|2E56|          Sushi Roll|Rice, seaweed, fi...|{670c8bcc5dafe069...|
|MINX|      Butter Chicken|Chicken, butter, ...|{670c8bcc5dafe069...|
|68ZP|            Pancakes|Flour, eggs, milk...|{670c8bcc5dafe069...|
|9DNV|    Margherita Pizza|Pizza dough, toma...|{670c8bcc5dafe069...|
|QMCI|      Butter Chicken|Chicken, butter, ...|{670c8bcc5dafe069...|
|C13Z| Spaghetti Carbonara|Spaghetti, eggs, ...|{670c8bcc5dafe069...|
+----+--------------------+--------------------+--------------------+
only showing top 20 rows

In [40]:
# Drop the id column before use
pdDF_dropped = pdDF.drop(['_id'], axis = 1)
pdSparkDF = spark.createDataFrame(pdDF_dropped)
pdSparkDF.show()

+----+--------------------+--------------------+
|Code|           Dish Name|         Ingredients|
+----+--------------------+--------------------+
|U0GT| Spaghetti Carbonara|Spaghetti, eggs, ...|
|V4WJ|          Beef Tacos|Beef, taco shells...|
|9U84|        Tom Yum Soup|Shrimp, lemongras...|
|OWSH|          Sushi Roll|Rice, seaweed, fi...|
|TPPS| Spaghetti Carbonara|Spaghetti, eggs, ...|
|PDYD|Chicken Caesar Salad|Chicken, romaine ...|
|R08D|            Pad Thai|Rice noodles, shr...|
|L7XN|            Pancakes|Flour, eggs, milk...|
|VNKN|      Butter Chicken|Chicken, butter, ...|
|KFC7|Chicken Caesar Salad|Chicken, romaine ...|
|Q2BE|    Margherita Pizza|Pizza dough, toma...|
|LK91|        Tom Yum Soup|Shrimp, lemongras...|
|5905|            Pad Thai|Rice noodles, shr...|
|H1L1|            Pancakes|Flour, eggs, milk...|
|2E56|          Sushi Roll|Rice, seaweed, fi...|
|MINX|      Butter Chicken|Chicken, butter, ...|
|68ZP|            Pancakes|Flour, eggs, milk...|
|9DNV|    Margherita Pizza|Pizza dough, toma...|
|QMCI|      Butter Chicken|Chicken, butter, ...|
|C13Z| Spaghetti Carbonara|Spaghetti, eggs, ...|
+----+--------------------+--------------------+
only showing top 20 rows

In [41]:
# # Stop the Spark session when done
# spark.stop()

In [42]:
df1 = pdSparkDF.toPandas()
df1

,Code,Dish Name,Ingredients
0,U0GT,Spaghetti Carbonara,"Spaghetti, eggs, pancetta, parmesan, black pepper"
1,V4WJ,Beef Tacos,"Beef, taco shells, lettuce, tomato, cheese, salsa"
2,9U84,Tom Yum Soup,"Shrimp, lemongrass, lime juice, chili, mushrooms"
3,OWSH,Sushi Roll,"Rice, seaweed, fish, cucumber, avocado"
4,TPPS,Spaghetti Carbonara,"Spaghetti, eggs, pancetta, parmesan, black pepper"
...,...,...,...
95,LCER,Tom Yum Soup,"Shrimp, lemongrass, lime juice, chili, mushrooms"
96,HS3J,Beef Tacos,"Beef, taco shells, lettuce, tomato, cheese, salsa"
97,2LJ1,Margherita Pizza,"Pizza dough, tomatoes, mozzarella, basil"
98,3TC8,Sushi Roll,"Rice, seaweed, fish, cucumber, avocado"
99,UFJJ,Pancakes,"Flour, eggs, milk, sugar, baking powder, syrup"

In [43]:
df2 = pd.read_csv('orders.csv')
df2

   Order ID       Full names Dish code
0     OD001    Amanda Howard      JLHK
1     OD001    Amanda Howard      UFJJ
2     OD002  Timothy Edwards      MB73
3     OD002  Timothy Edwards      3XM4
4     OD002  Timothy Edwards      LK91
..      ...              ...       ...
85    OD047   Patrick Rivera      6C5Z
86    OD048  Steven Phillips      KIMY
87    OD048  Steven Phillips      3TC8
88    OD049      Susan White      KHA3
89    OD050  Timothy Edwards      ZYG5

[90 rows x 3 columns]

In [44]:
joined_df = pd.merge(df1, df2, left_on='Code', right_on='Dish code', how='inner')
joined_df

,Code,Dish Name,Ingredients,Order ID,Full names,Dish code
0,U0GT,Spaghetti Carbonara,"Spaghetti, eggs, pancetta, parmesan, black pepper",OD012,Megan Evans,U0GT
1,U0GT,Spaghetti Carbonara,"Spaghetti, eggs, pancetta, parmesan, black pepper",OD041,Rebecca Flores,U0GT
2,V4WJ,Beef Tacos,"Beef, taco shells, lettuce, tomato, cheese, salsa",OD017,Frank Stewart,V4WJ
3,9U84,Tom Yum Soup,"Shrimp, lemongrass, lime juice, chili, mushrooms",OD004,Angela Campbell,9U84
4,OWSH,Sushi Roll,"Rice, seaweed, fish, cucumber, avocado",OD026,Karen Thompson,OWSH
...,...,...,...,...,...,...
85,2LJ1,Margherita Pizza,"Pizza dough, tomatoes, mozzarella, basil",OD029,Kimberly Turner,2LJ1
86,3TC8,Sushi Roll,"Rice, seaweed, fish, cucumber, avocado",OD016,Emily Johnson,3TC8
87,3TC8,Sushi Roll,"Rice, seaweed, fish, cucumber, avocado",OD048,Steven Phillips,3TC8
88,UFJJ,Pancakes,"Flour, eggs, milk, sugar, baking powder, syrup",OD001,Amanda Howard,UFJJ
89,UFJJ,Pancakes,"Flour, eggs, milk, sugar, baking powder, syrup",OD018,Rebecca Flores,UFJJ

In [48]:
# Tạo từ điển ánh xạ từ mã món ăn sang tên món
code_to_name = dict(zip(joined_df['Code'], joined_df['Dish Name']))

grouped = joined_df.groupby(['Order ID', 'Full names'])['Code'].apply(list).reset_index()

# Tạo danh sách tài liệu
documents = []
for _, row in grouped.iterrows():
    dishes = [{'code': code, 'dish name': code_to_name.get(code, 'Unknown')} for code in row['Code']]
    doc = {
        'Order ID': row['Order ID'],
        'Full name': row['Full names'],
        'Dishes': dishes
    }
    documents.append(doc)

# # Hàm tạo document
# def create_document(row):
#     codes = row['Code'].split(',')
#     dishes = [{'code': code, 'dish name': code_to_name.get(code, 'Unknown')} for code in codes]
#     return {
#         'Order ID': row['Order ID'],
#         'Full name': row['Full names'],
#         'Dishes': dishes
#     }

# # Áp dụng cho từng dòng
# documents = joined_df.apply(create_document, axis=1).tolist()

# In kết quả
for doc in documents:
    print(doc)

{'Order ID': 'OD001', 'Full name': 'Amanda Howard', 'Dishes': [{'code': 'JLHK', 'dish name': 'Butter Chicken'}, {'code': 'UFJJ', 'dish name': 'Pancakes'}]}
{'Order ID': 'OD002', 'Full name': 'Timothy Edwards', 'Dishes': [{'code': 'LK91', 'dish name': 'Tom Yum Soup'}, {'code': 'MB73', 'dish name': 'Sushi Roll'}, {'code': '3XM4', 'dish name': 'Tom Yum Soup'}]}
{'Order ID': 'OD003', 'Full name': 'Andrew Scott', 'Dishes': [{'code': 'QMCI', 'dish name': 'Butter Chicken'}, {'code': 'XWB6', 'dish name': 'Pad Thai'}]}
{'Order ID': 'OD004', 'Full name': 'Angela Campbell', 'Dishes': [{'code': '9U84', 'dish name': 'Tom Yum Soup'}, {'code': 'G568', 'dish name': 'Pancakes'}]}
{'Order ID': 'OD005', 'Full name': 'Anthony Sanders', 'Dishes': [{'code': 'CFUS', 'dish name': 'Margherita Pizza'}, {'code': 'SBRM', 'dish name': 'Spaghetti Carbonara'}]}
{'Order ID': 'OD006', 'Full name': 'Ashley Perez', 'Dishes': [{'code': 'IJS3', 'dish name': 'Margherita Pizza'}, {'code': '2F00', 'dish name': 'Spaghetti Carbonara'}]}
{'Order ID': 'OD007', 'Full name': 'Rebecca Flores', 'Dishes': [{'code': 'MINX', 'dish name': 'Butter Chicken'}]}
{'Order ID': 'OD008', 'Full name': 'Brenda Gray', 'Dishes': [{'code': 'XWB6', 'dish name': 'Pad Thai'}]}
{'Order ID': 'OD009', 'Full name': 'Brian Gonzalez', 'Dishes': [{'code': 'UQT2', 'dish name': 'Sushi Roll'}]}
{'Order ID': 'OD010', 'Full name': 'Charles Lewis', 'Dishes': [{'code': 'UQT2', 'dish name': 'Sushi Roll'}]}
{'Order ID': 'OD011', 'Full name': 'Christina Mitchell', 'Dishes': [{'code': 'S98R', 'dish name': 'Margherita Pizza'}]}
{'Order ID': 'OD012', 'Full name': 'Megan Evans', 'Dishes': [{'code': 'U0GT', 'dish name': 'Spaghetti Carbonara'}]}
{'Order ID': 'OD013', 'Full name': 'Daniel Anderson', 'Dishes': [{'code': 'YXON', 'dish name': 'Pad Thai'}]}
{'Order ID': 'OD014', 'Full name': 'David Wilson', 'Dishes': [{'code': 'UKMD', 'dish name': 'Vegetable Stir-fry'}]}
{'Order ID': 'OD015', 'Full name': 'Elizabeth Baker', 'Dishes': [{'code': 'DVAW', 'dish name': 'Chicken Caesar Salad'}]}
{'Order ID': 'OD016', 'Full name': 'Emily Johnson', 'Dishes': [{'code': '3TC8', 'dish name': 'Sushi Roll'}]}
{'Order ID': 'OD017', 'Full name': 'Frank Stewart', 'Dishes': [{'code': 'V4WJ', 'dish name': 'Beef Tacos'}]}
{'Order ID': 'OD018', 'Full name': 'Rebecca Flores', 'Dishes': [{'code': 'UFJJ', 'dish name': 'Pancakes'}]}
{'Order ID': 'OD019', 'Full name': 'James Taylor', 'Dishes': [{'code': '5T58', 'dish name': 'Pad Thai'}]}
{'Order ID': 'OD020', 'Full name': 'Patrick Rivera', 'Dishes': [{'code': 'L5N4', 'dish name': 'Margherita Pizza'}, {'code': 'CUJY', 'dish name': 'Butter Chicken'}]}
{'Order ID': 'OD021', 'Full name': 'Jessica Martinez', 'Dishes': [{'code': '52C4', 'dish name': 'Sushi Roll'}, {'code': 'QE8E', 'dish name': 'Butter Chicken'}]}
{'Order ID': 'OD022', 'Full name': 'Timothy Edwards', 'Dishes': [{'code': 'KFC7', 'dish name': 'Chicken Caesar Salad'}, {'code': 'LCER', 'dish name': 'Tom Yum Soup'}]}
{'Order ID': 'OD023', 'Full name': 'Joseph Harris', 'Dishes': [{'code': 'VNKN', 'dish name': 'Butter Chicken'}, {'code': 'Q8VK', 'dish name': 'Beef Tacos'}]}
{'Order ID': 'OD024', 'Full name': 'Joshua Parker', 'Dishes': [{'code': 'R08D', 'dish name': 'Pad Thai'}, {'code': 'C13Z', 'dish name': 'Spaghetti Carbonara'}]}
{'Order ID': 'OD025', 'Full name': 'Justin Reed', 'Dishes': [{'code': 'COW5', 'dish name': 'Tom Yum Soup'}, {'code': '8YTF', 'dish name': 'Sushi Roll'}]}
{'Order ID': 'OD026', 'Full name': 'Karen Thompson', 'Dishes': [{'code': 'OWSH', 'dish name': 'Sushi Roll'}, {'code': 'GWR5', 'dish name': 'Chicken Caesar Salad'}]}
{'Order ID': 'OD027', 'Full name': 'Katherine Morris', 'Dishes': [{'code': '30Y9', 'dish name': 'Sushi Roll'}]}
{'Order ID': 'OD028', 'Full name': 'Kevin Hall', 'Dishes': [{'code': 'JLHK', 'dish name': 'Butter Chicken'}]}
{'Order ID': 'OD029', 'Full name': 'Kimberly Turner', 'Dishes': [{'code': '2LJ1', 'dish name': 'Margherita Pizza'}]}
{'Order ID': 'OD030', 'Full name': 'Laura Thomas', 'Dishes': [{'code': 'L5N4', 'dish name': 'Margherita Pizza'}]}
{'Order ID': 'OD031', 'Full name': 'Linda Walker', 'Dishes': [{'code': 'ZNKS', 'dish name': 'Pad Thai'}]}
{'Order ID': 'OD032', 'Full name': 'Mary Lee', 'Dishes': [{'code': '85GT', 'dish name': 'Beef Tacos'}, {'code': '3XM4', 'dish name': 'Tom Yum Soup'}]}
{'Order ID': 'OD033', 'Full name': 'Matthew King', 'Dishes': [{'code': 'GPQL', 'dish name': 'Butter Chicken'}, {'code': 'GU6A', 'dish name': 'Beef Tacos'}]}
{'Order ID': 'OD034', 'Full name': 'Megan Evans', 'Dishes': [{'code': 'NE5U', 'dish name': 'Chicken Caesar Salad'}, {'code': 'Q8VK', 'dish name': 'Beef Tacos'}]}
{'Order ID': 'OD035', 'Full name': 'Michael Brown', 'Dishes': [{'code': 'XZ80', 'dish name': 'Pancakes'}, {'code': 'HS3J', 'dish name': 'Beef Tacos'}]}
{'Order ID': 'OD036', 'Full name': 'Michelle Ward', 'Dishes': [{'code': 'IJS3', 'dish name': 'Margherita Pizza'}, {'code': '6C5Z', 'dish name': 'Chicken Caesar Salad'}]}
{'Order ID': 'OD037', 'Full name': 'Nancy Green', 'Dishes': [{'code': '7104', 'dish name': 'Beef Tacos'}, {'code': 'IJS3', 'dish name': 'Margherita Pizza'}, {'code': 'DVAW', 'dish name': 'Chicken Caesar Salad'}]}
{'Order ID': 'OD038', 'Full name': 'Patricia Clark', 'Dishes': [{'code': 'G31C', 'dish name': 'Butter Chicken'}, {'code': 'E9SP', 'dish name': 'Pad Thai'}, {'code': 'TF2F', 'dish name': 'Vegetable Stir-fry'}, {'code': 'QE8E', 'dish name': 'Butter Chicken'}]}
{'Order ID': 'OD039', 'Full name': 'Patrick Rivera', 'Dishes': [{'code': 'OWSH', 'dish name': 'Sushi Roll'}, {'code': '2F00', 'dish name': 'Spaghetti Carbonara'}, {'code': '52K0', 'dish name': 'Pad Thai'}, {'code': 'XWB6', 'dish name': 'Pad Thai'}]}
{'Order ID': 'OD040', 'Full name': 'Paul Roberts', 'Dishes': [{'code': 'KFC7', 'dish name': 'Chicken Caesar Salad'}, {'code': 'YLTP', 'dish name': 'Chicken Caesar Salad'}, {'code': 'SHMA', 'dish name': 'Spaghetti Carbonara'}]}
{'Order ID': 'OD041', 'Full name': 'Rebecca Flores', 'Dishes': [{'code': 'U0GT', 'dish name': 'Spaghetti Carbonara'}, {'code': 'E9SP', 'dish name': 'Pad Thai'}, {'code': 'GM62', 'dish name': 'Vegetable Stir-fry'}]}
{'Order ID': 'OD042', 'Full name': 'Richard Adams', 'Dishes': [{'code': 'MB6D', 'dish name': 'Butter Chicken'}, {'code': 'ZYG5', 'dish name': 'Spaghetti Carbonara'}, {'code': 'GWR5', 'dish name': 'Chicken Caesar Salad'}]}
{'Order ID': 'OD043', 'Full name': 'Robert Moore', 'Dishes': [{'code': 'ZGTZ', 'dish name': 'Chicken Caesar Salad'}, {'code': 'RXY4', 'dish name': 'Beef Tacos'}]}
{'Order ID': 'OD044', 'Full name': 'Megan Evans', 'Dishes': [{'code': '5905', 'dish name': 'Pad Thai'}, {'code': '9DNV', 'dish name': 'Margherita Pizza'}]}
{'Order ID': 'OD045', 'Full name': 'Samuel Peterson', 'Dishes': [{'code': 'PDYD', 'dish name': 'Chicken Caesar Salad'}, {'code': '9Z2M', 'dish name': 'Vegetable Stir-fry'}]}
{'Order ID': 'OD046', 'Full name': 'Sarah Davis', 'Dishes': [{'code': '9DNV', 'dish name': 'Margherita Pizza'}, {'code': 'E9SP', 'dish name': 'Pad Thai'}, {'code': 'XWB6', 'dish name': 'Pad Thai'}]}
{'Order ID': 'OD047', 'Full name': 'Patrick Rivera', 'Dishes': [{'code': '6LVB', 'dish name': 'Sushi Roll'}, {'code': '6C5Z', 'dish name': 'Chicken Caesar Salad'}]}
{'Order ID': 'OD048', 'Full name': 'Steven Phillips', 'Dishes': [{'code': 'KIMY', 'dish name': 'Pancakes'}, {'code': '3TC8', 'dish name': 'Sushi Roll'}]}
{'Order ID': 'OD049', 'Full name': 'Susan White', 'Dishes': [{'code': 'KHA3', 'dish name': 'Spaghetti Carbonara'}]}
{'Order ID': 'OD050', 'Full name': 'Timothy Edwards', 'Dishes': [{'code': 'ZYG5', 'dish name': 'Spaghetti Carbonara'}]}

In [50]:
from pymongo import MongoClient

# Khởi tạo kết nối tới MongoDB (local)
client = MongoClient("mongodb+srv://student:student@bigdata.zyjwsrz.mongodb.net/")

# Khai báo thông tin
db = client["assignments"]
student_id = "22120071"
collection = db[student_id]

collection.insert_many(documents)

print(f"Đã ghi {len(documents)} tài liệu vào collection '{student_id}' trong database 'assignments'")

Đã ghi 50 tài liệu vào collection '22120071' trong database 'assignments'

In [51]:
spark.stop()
client.close()